services:
  app:
    build: .
    container_name: product-manager-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DB_URI=${DB_URI:-mongodb://mongodb:27018/product-manager}
      - TEST_DB_URI=${TEST_DB_URI:-mongodb://mongodb:27018/product-manager-test}
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - product-manager-network

  mongodb:
    image: mongo:latest
    container_name: product-manager-mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - product-manager-network

networks:
  product-manager-network:
    driver: bridge

volumes:
  mongodb_data: