@baseUrl = http://localhost:3000

###
GET {{baseUrl}}


###


###
POST {{baseUrl}}/product
Content-Type: application/json

{
  "name": "Test Product",
  "price": 100,
  "description": "This is a test product",
  "stock": 50
}
###
